# fly.toml app configuration file generated for bill-search on 2025-07-09T12:58:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bill-search'
primary_region = 'dfw'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
