name: Daily Bill Scraper

on:
  schedule:
    # Run daily at 6 AM EST (11 AM UTC)
    - cron: '0 11 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back for bills'
        required: false
        default: '1'
        type: string
      mode:
        description: 'Scraper mode'
        required: false
        default: 'daily'
        type: choice
        options:
          - daily
          - test

jobs:
  scrape-bills:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd backend/scraper
        pip install -r requirements.txt
    
    - name: Run bill scraper
      env:
        CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        cd backend/scraper
        python main.py --mode ${{ github.event.inputs.mode || 'daily' }} --days ${{ github.event.inputs.days || '1' }}

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-logs
        path: backend/scraper/*.log

    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Daily Bill Scraper Failed',
            body: `The daily bill scraper workflow failed.
            
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Time:** ${{ github.run_number }}
            **Mode:** ${{ github.event.inputs.mode || 'daily' }}
            **Days:** ${{ github.event.inputs.days || '1' }}
            
            Please check the logs and fix any issues.`,
            labels: ['bug', 'scraper']
          }) 